### ISSUE TITLE
team builder improvements

### ISSUE THREAD

**Issue by howardchung** [odota/underlords-web#14]
* order alliances so completed ones come first
* serialize/deserialize selected heroes to URL (shareable links)
* clicking on an alliance highlights remaining heroes with that alliance

**Comment by Argn0** [comment]
I have already implemented these functionalities. Sorry, I forgot to mention it in the PR.

-Clicking the icon of an active alliance, applies a filter.
-URL with heroes is shareable
-active alliances are sorted by their level(completed ones come first)

**Comment by howardchung** [comment]
OK, I didn't see them in the netlify preview but maybe I clicked the wrong link or got a cached version.

I found one small issue which is that the alliance text doesn't have the text substitution for variable values:
https://master--openunderlords.netlify.com/en/builder?team=axe,beastmaster,disruptor,juggernaut

**Comment by Argn0** [comment]
> OK, I didn't see them in the netlify preview but maybe I clicked the wrong link or got a cached version.
> 
> I found one small issue which is that the alliance text doesn't have the text substitution for variable values:
> https://master--openunderlords.netlify.com/en/builder?team=axe,beastmaster,disruptor,juggernaut

Hmm, it seems like that issue appeared with the underlordsconstants update today.

**Comment by Argn0** [comment]
ok the values were fixed in https://github.com/odota/underlordsconstants/commit/61979f75101cf048fde87865ea4127965eb27245
