### ISSUE TITLE
Alliance icons without background

### ISSUE THREAD

**Issue by lmao-emerald** [odota/underlords-web#20]
I'm not very good at Github, but would you change the current alliance icons with ones without background if I make them all? I just made one for showing purposes:
https://i.imgur.com/tpDhbeY.png
https://i.imgur.com/0OjUokx.png

**Comment by howardchung** [comment]
Sure, that would be awesome! How are you making them? The raw alliance images are checked into this repo, but need to be assembled for the ones used in-game.

**Comment by lmao-emerald** [comment]
I just got the jpg ones from openunderlords, deleted the background and border with Photoshop, added a new border with photoshop and saved it without any background.
I posted a few images here in the simple process I used: https://imgur.com/a/azfsGNz
If everything goes well today I should have all of them finished before the day ends

**Comment by lmao-emerald** [comment]
Done!
[alliances.zip](https://github.com/odota/underlords-web/files/3386289/alliances.zip)

**Comment by howardchung** [comment]
checked in new images
