### ISSUE TITLE
Fix menu width

### ISSUE THREAD

**Issue by olegshulyakov** [odota/underlords-web#23]
Current width of left menu is a little bit bigger than it is needed.
![image](https://user-images.githubusercontent.com/4524455/61795541-5509a400-ae2c-11e9-97ee-be8da58e4069.png)

Current value is 280px, I propose to change it to 250px.

**Comment by howardchung** [comment]
Seems fine to me. Do you want to submit a PR?

**Comment by olegshulyakov** [comment]
@howardchung sorry for misleading, the scroll on the bottom of the menu. There should not be no scroll since there is enought space to display menu items.

May be it is even better to not display hamburger on wide screens like it is done in opendota.

**Comment by albertcui** [comment]
I've removed the hamburger menu on desktop. Thanks!
