### ISSUE TITLE
Teambuilder tool

### ISSUE THREAD

**Issue by howardchung** [odota/underlords-web#7]
Suggestion: Create a tool for simulating combinations of heroes

- [ ] List alliances + effects
- [ ] Re-roll simulator + probability of getting a given team
- [ ] Weaknesses of a given team combination 
- [ ] Saving and sharing combinations with others
- [ ] Show how the team would develop through the game (i.e. v1...vN of a team)
- [ ] Build aggregated tier lists off of teams people build

**Comment by albertcui** [comment]
The big thing for me is just being able to pick a group of heroes and show which alliances they make. Less important, but still nice, would be allowing the user to place the heroes on a board to fiddle with builds that require positioning. Letting players assign items and stars to the heroes would be another plus, as would a nice display of their post-alliance/items stats, and a total gold cost of the team and individual units. Now that we know the roll chance for each tier of hero, you could even run some statistical analysis to determine pivotal levels in a comp.
