### ISSUE TITLE
Browser Language

### ISSUE THREAD

**Issue by ozbra** [odota/underlords-web#8]
Please don't force users to browser language. I have tried to see the content in English but it redirects me everytime to browser language.

**Comment by albertcui** [comment]
There's a globe icon in the top left where you can change your language. It should persist if you change it. If it isn't it's a bug, so please let me know if it's not working!

**Comment by ozbra** [comment]
> There's a globe icon in the top left where you can change your language. It should persist if you change it. If it isn't it's a bug, so please let me know if it's not working!

right now it is working. Right now even storing the selected language option and navigation with selected language path.

**Comment by howardchung** [comment]
I've heard feedback from European users that they often prefer English, but it won't default to that for them since their browser indicates something different.

**Comment by ozbra** [comment]
Yes, most of the European uses are playing the game also in English, if they know English. My suggestion on that can be, Move bug report to right and Language settings to left of bug reports, and maybe use a flag or something else to take more attention. Right now globe icon is not that much understanding at first side and also it looks like a part of bug report.

**Comment by albertcui** [comment]
I've changed the icon to a "translate" icon to make it more obvious what it does.
